// Auto-generated by scripts/upload-images-to-blob.mjs
// Maps local /images/explore/* paths to Vercel Blob URLs

const BLOB_URLS: Record<string, string> = {
  "/images/explore/about-hero.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/about-hero.jpg",
  "/images/explore/blog-ancient.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/blog-ancient.jpg",
  "/images/explore/blog-china-first.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/blog-china-first.jpg",
  "/images/explore/blog-cycling.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/blog-cycling.jpg",
  "/images/explore/blog-dupes.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/blog-dupes.jpg",
  "/images/explore/blog-great-wall.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/blog-great-wall.jpg",
  "/images/explore/blog-stargazing.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/blog-stargazing.jpg",
  "/images/explore/dest-africa.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-africa.jpg",
  "/images/explore/dest-asia.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-asia.jpg",
  "/images/explore/dest-australasia.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-australasia.jpg",
  "/images/explore/dest-caribbean.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-caribbean.jpg",
  "/images/explore/dest-central-america.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-central-america.jpg",
  "/images/explore/dest-europe.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-europe.jpg",
  "/images/explore/dest-middle-east.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-middle-east.jpg",
  "/images/explore/dest-north-america.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-north-america.jpg",
  "/images/explore/dest-polar.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-polar.jpg",
  "/images/explore/dest-south-america.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/dest-south-america.jpg",
  "/images/explore/exp-boat.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-boat.jpg",
  "/images/explore/exp-cycling.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-cycling.jpg",
  "/images/explore/exp-discovery.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-discovery.jpg",
  "/images/explore/exp-family.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-family.jpg",
  "/images/explore/exp-food.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-food.jpg",
  "/images/explore/exp-polar.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-polar.jpg",
  "/images/explore/exp-solo.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-solo.jpg",
  "/images/explore/exp-upgraded.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-upgraded.jpg",
  "/images/explore/exp-walking.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-walking.jpg",
  "/images/explore/exp-wildlife.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/exp-wildlife.jpg",
  "/images/explore/hero-mountains.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/hero-mountains.jpg",
  "/images/explore/hero-santorini.png": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/hero-santorini.png",
  "/images/explore/promo-micro-retirement.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/promo-micro-retirement.jpg",
  "/images/explore/promo-new-trips.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/promo-new-trips.jpg",
  "/images/explore/promo-polar.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/promo-polar.jpg",
  "/images/explore/promo-south-america.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/promo-south-america.jpg",
  "/images/explore/trip-amalfi.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/trip-amalfi.jpg",
  "/images/explore/trip-cuba.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/trip-cuba.jpg",
  "/images/explore/trip-japan.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/trip-japan.jpg",
  "/images/explore/trip-patagonia.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/trip-patagonia.jpg",
  "/images/explore/trip-south-africa.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/trip-south-africa.jpg",
  "/images/explore/hero-energy.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/hero-energy.jpg",
  "/images/explore/eon-strom.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/eon-strom.jpg",
  "/images/explore/eon-solar.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/eon-solar.jpg",
  "/images/explore/eon-emobility.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/eon-emobility.jpg",
  "/images/explore/eon-waermepumpe.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/eon-waermepumpe.jpg",
  "/images/explore/eon-smarthome.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/eon-smarthome.jpg",
  "/images/explore/eon-gas.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/eon-gas.jpg",
  "/images/explore/blog-energy-tips.jpg": "https://nqlmkxqox66ff90a.public.blob.vercel-storage.com/explore/blog-energy-tips.jpg"
};

/** Allowed external hostnames for next/image */
const ALLOWED_HOSTS = [
  "nqlmkxqox66ff90a.public.blob.vercel-storage.com",
  "images.ctfassets.net",
  "explore-live.s3.eu-west-1.amazonaws.com",
  "explore-qa.s3.eu-west-1.amazonaws.com",
  "s3.eu-west-1.amazonaws.com",
];

/**
 * Resolves an image path to its Vercel Blob URL.
 * Falls back to a safe default if the URL points to an unconfigured host,
 * preventing next/image hostname errors.
 */
export function blobUrl(localPath: string): string {
  if (BLOB_URLS[localPath]) return BLOB_URLS[localPath];

  // If it's an external URL, only allow known hosts -- otherwise use a fallback
  if (localPath.startsWith("http")) {
    try {
      const { hostname } = new URL(localPath);
      if (ALLOWED_HOSTS.some((h) => hostname === h || hostname.endsWith(`.${h}`))) {
        return localPath;
      }
    } catch { /* invalid URL */ }
    // Unknown external host -- return a safe blob fallback
    return BLOB_URLS["/images/explore/hero-energy.jpg"] || localPath;
  }

  return localPath;
}

export default BLOB_URLS;
