// Tour data for Explore travel site
export interface TourDeparture {
  id: string
  startDate: string
  endDate: string
  price: number
  originalPrice?: number
  status: "Available" | "Limited" | "Guaranteed" | "Sold Out"
  note?: string
}

export interface TourItineraryDay {
  day: number
  title: string
  description: string
  meals?: string
  accommodation?: string
}

export interface TourDetail {
  slug: string
  title: string
  destination: string
  country: string
  tripType: string
  duration: string
  durationDays: number
  groupSize: string
  physicalRating: number
  maxAltitude?: string
  price: number
  originalPrice?: number
  imageUrl: string
  galleryImages: string[]
  tripCode: string
  overview: string
  highlights: string[]
  included: string[]
  notIncluded: string[]
  itinerary: TourItineraryDay[]
  departures: TourDeparture[]
  relatedSlugs: string[]
}

export const TOURS: Record<string, TourDetail> = {
  "japan-in-depth": {
    slug: "japan-in-depth",
    title: "Japan In Depth - Footsteps of the Shogun",
    destination: "Japan",
    country: "Japan",
    tripType: "Discovery",
    duration: "12 Days",
    durationDays: 12,
    groupSize: "6-16",
    physicalRating: 2,
    price: 4245,
    originalPrice: 4545,
    imageUrl: "/images/explore/eon-strom.jpg",
    galleryImages: ["/images/explore/eon-strom.jpg"],
    tripCode: "JS",
    overview:
      "Discover the very best of Japan on this 12-day small group tour that takes you from the buzzing streets of Tokyo through the cultural heartland to the tranquil temples of Kyoto. Experience traditional ryokan stays, sample authentic Japanese cuisine, witness the beauty of Mount Fuji and explore ancient samurai towns. With an expert local tour leader, you'll get beneath the surface of this fascinating country.",
    highlights: [
      "Explore the vibrant Shibuya crossing and Meiji Shrine in Tokyo",
      "Stay in a traditional Japanese ryokan with onsen bathing",
      "Visit the iconic Fushimi Inari shrine with its thousands of torii gates",
      "Discover the samurai district of Kanazawa",
      "Take the bullet train through stunning Japanese countryside",
      "Experience a traditional tea ceremony in Kyoto",
    ],
    included: [
      "11 nights accommodation",
      "All breakfasts, 3 lunches, 4 dinners",
      "Bullet train tickets",
      "Expert English-speaking tour leader",
      "All entrance fees and activities as listed",
      "Airport transfers on day 1 and last day",
    ],
    notIncluded: [
      "International flights",
      "Travel insurance",
      "Meals not listed",
      "Personal expenses and tips",
      "Visa (if required)",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Tokyo", description: "Arrive at Tokyo Narita Airport and transfer to your hotel. Meet your tour leader and group for a welcome briefing and dinner.", meals: "Dinner", accommodation: "Hotel in Shinjuku" },
      { day: 2, title: "Tokyo exploration", description: "Full day exploring Tokyo including Meiji Shrine, Harajuku, Shibuya crossing and the Tsukiji Outer Market. Evening free to explore.", meals: "Breakfast", accommodation: "Hotel in Shinjuku" },
      { day: 3, title: "Tokyo to Hakone", description: "Travel to Hakone and enjoy views of Mount Fuji. Take a cruise on Lake Ashi and ride the Hakone Ropeway.", meals: "Breakfast, Lunch", accommodation: "Ryokan in Hakone" },
      { day: 4, title: "Hakone to Takayama", description: "Travel by train through stunning mountain scenery to the beautiful town of Takayama, known for its preserved Edo-era streets.", meals: "Breakfast", accommodation: "Hotel in Takayama" },
      { day: 5, title: "Takayama & Shirakawago", description: "Morning visit to Takayama's morning markets. Afternoon excursion to the UNESCO World Heritage village of Shirakawago.", meals: "Breakfast, Dinner", accommodation: "Hotel in Takayama" },
      { day: 6, title: "Takayama to Kanazawa", description: "Travel to Kanazawa and visit the stunning Kenrokuen Garden, one of Japan's three great gardens. Explore the samurai and geisha districts.", meals: "Breakfast", accommodation: "Hotel in Kanazawa" },
      { day: 7, title: "Kanazawa to Kyoto", description: "Bullet train to Kyoto. Afternoon visit to the Golden Pavilion (Kinkaku-ji) and the Nishiki Market.", meals: "Breakfast, Lunch", accommodation: "Hotel in Kyoto" },
      { day: 8, title: "Kyoto temples", description: "Full day in Kyoto visiting Fushimi Inari shrine, Kiyomizu-dera temple and the bamboo grove of Arashiyama.", meals: "Breakfast", accommodation: "Hotel in Kyoto" },
      { day: 9, title: "Nara day trip", description: "Day trip to Nara to see the Great Buddha at Todai-ji temple and the friendly deer in Nara Park.", meals: "Breakfast, Dinner", accommodation: "Hotel in Kyoto" },
      { day: 10, title: "Kyoto tea ceremony", description: "Morning tea ceremony experience. Afternoon free for personal exploration or optional activities.", meals: "Breakfast, Lunch", accommodation: "Hotel in Kyoto" },
      { day: 11, title: "Kyoto to Hiroshima", description: "Bullet train to Hiroshima. Visit the Peace Memorial Museum and Park. Ferry to Miyajima Island to see the floating torii gate.", meals: "Breakfast, Dinner", accommodation: "Hotel in Hiroshima" },
      { day: 12, title: "Departure", description: "Transfer to Hiroshima station or airport for onward travel. Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "JS-2026-04-12", startDate: "2026-04-12", endDate: "2026-04-23", price: 4245, originalPrice: 4545, status: "Guaranteed" },
      { id: "JS-2026-05-03", startDate: "2026-05-03", endDate: "2026-05-14", price: 4245, originalPrice: 4545, status: "Available" },
      { id: "JS-2026-05-17", startDate: "2026-05-17", endDate: "2026-05-28", price: 4495, status: "Limited" },
      { id: "JS-2026-06-07", startDate: "2026-06-07", endDate: "2026-06-18", price: 4245, originalPrice: 4545, status: "Available" },
      { id: "JS-2026-09-06", startDate: "2026-09-06", endDate: "2026-09-17", price: 4495, status: "Available" },
      { id: "JS-2026-09-20", startDate: "2026-09-20", endDate: "2026-10-01", price: 4495, status: "Guaranteed" },
      { id: "JS-2026-10-04", startDate: "2026-10-04", endDate: "2026-10-15", price: 4695, status: "Available", note: "Autumn colours" },
      { id: "JS-2026-10-18", startDate: "2026-10-18", endDate: "2026-10-29", price: 4695, status: "Limited", note: "Autumn colours" },
      { id: "JS-2026-11-08", startDate: "2026-11-08", endDate: "2026-11-19", price: 4245, status: "Available" },
      { id: "JS-2027-03-21", startDate: "2027-03-21", endDate: "2027-04-01", price: 4795, status: "Available", note: "Cherry blossom" },
    ],
    relatedSlugs: ["amalfi-coast-walking", "cycle-cuba", "south-africa-eswatini"],
  },
  "amalfi-coast-walking": {
    slug: "amalfi-coast-walking",
    title: "Amalfi Coast Walking - Agriturismo",
    destination: "Italy",
    country: "Italy",
    tripType: "Walking",
    duration: "8 Days",
    durationDays: 8,
    groupSize: "8-16",
    physicalRating: 3,
    price: 1495,
    imageUrl: "/images/explore/eon-solar.jpg",
    galleryImages: ["/images/explore/eon-solar.jpg"],
    tripCode: "NAW",
    overview:
      "Walk through the spectacular scenery of southern Italy's Amalfi Coast on this 8-day walking holiday. Stay in a family-run agriturismo set among lemon groves and olive trees, and enjoy daily walks along stunning coastal paths with breathtaking sea views. Discover picturesque villages, taste local limoncello, and swim in crystal-clear waters.",
    highlights: [
      "Walk the famous Path of the Gods with panoramic coast views",
      "Stay in a beautiful agriturismo among lemon groves",
      "Visit the colourful cliffside village of Positano",
      "Explore the ancient ruins of Pompeii",
      "Enjoy authentic Italian home-cooking",
      "Swim in the Mediterranean at secluded beaches",
    ],
    included: [
      "7 nights accommodation in agriturismo",
      "All breakfasts, 3 lunches, 5 dinners",
      "Expert walking guide",
      "All transport between walks",
      "Entrance to Pompeii",
    ],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Naples", description: "Transfer from Naples airport to your agriturismo on the Amalfi Coast. Welcome dinner with the group.", meals: "Dinner", accommodation: "Agriturismo" },
      { day: 2, title: "Ravello & Amalfi Walk", description: "Walk from Ravello down through terraced gardens to the coastal town of Amalfi. Approx 12km, 5hrs.", meals: "Breakfast, Dinner", accommodation: "Agriturismo" },
      { day: 3, title: "Path of the Gods", description: "The famous Sentiero degli Dei, a stunning cliff-top path with incredible views. Approx 10km, 4hrs.", meals: "Breakfast, Lunch, Dinner", accommodation: "Agriturismo" },
      { day: 4, title: "Positano", description: "Walk down to the picturesque village of Positano. Afternoon free to explore and swim.", meals: "Breakfast", accommodation: "Agriturismo" },
      { day: 5, title: "Valle delle Ferriere", description: "Walk through the Valley of the Mills, a hidden nature reserve with waterfalls. Approx 8km, 3.5hrs.", meals: "Breakfast, Lunch, Dinner", accommodation: "Agriturismo" },
      { day: 6, title: "Pompeii excursion", description: "Full day excursion to the ancient Roman city of Pompeii with guided tour.", meals: "Breakfast, Dinner", accommodation: "Agriturismo" },
      { day: 7, title: "Coastal walk & cooking class", description: "Morning coastal walk. Afternoon Italian cooking class at the agriturismo.", meals: "Breakfast, Lunch, Dinner", accommodation: "Agriturismo" },
      { day: 8, title: "Departure", description: "Transfer to Naples airport. Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "NAW-2026-04-18", startDate: "2026-04-18", endDate: "2026-04-25", price: 1495, status: "Guaranteed" },
      { id: "NAW-2026-05-02", startDate: "2026-05-02", endDate: "2026-05-09", price: 1595, status: "Available" },
      { id: "NAW-2026-05-16", startDate: "2026-05-16", endDate: "2026-05-23", price: 1595, status: "Limited" },
      { id: "NAW-2026-06-06", startDate: "2026-06-06", endDate: "2026-06-13", price: 1695, status: "Available" },
      { id: "NAW-2026-09-05", startDate: "2026-09-05", endDate: "2026-09-12", price: 1595, status: "Available" },
      { id: "NAW-2026-09-19", startDate: "2026-09-19", endDate: "2026-09-26", price: 1495, status: "Available" },
      { id: "NAW-2026-10-03", startDate: "2026-10-03", endDate: "2026-10-10", price: 1395, status: "Available" },
    ],
    relatedSlugs: ["japan-in-depth", "adventures-in-patagonia", "cycle-cuba"],
  },
  "adventures-in-patagonia": {
    slug: "adventures-in-patagonia",
    title: "Adventures in Patagonia",
    destination: "Argentina & Chile",
    country: "Argentina",
    tripType: "Discovery",
    duration: "14 Days",
    durationDays: 14,
    groupSize: "6-16",
    physicalRating: 3,
    price: 5065,
    imageUrl: "/images/explore/eon-emobility.jpg",
    galleryImages: ["/images/explore/eon-emobility.jpg"],
    tripCode: "PA",
    overview:
      "Explore the dramatic landscapes of Patagonia on this 14-day adventure through Argentina and Chile. From the glaciers of Perito Moreno to the granite spires of Torres del Paine, this trip showcases the very best of South America's wildest region.",
    highlights: [
      "Witness the mighty Perito Moreno glacier calving into the lake",
      "Trek in Torres del Paine National Park",
      "Cross the Andes from Argentina to Chile",
      "Spot condors, guanacos and rheas",
      "Explore colourful Buenos Aires",
    ],
    included: ["13 nights accommodation", "All breakfasts, 5 lunches, 6 dinners", "Expert tour leader", "All internal transport", "National park entrance fees"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Buenos Aires", description: "Arrive in Buenos Aires. Welcome meeting and dinner.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Buenos Aires", description: "City tour of Buenos Aires including La Boca and San Telmo.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 3, title: "Fly to El Calafate", description: "Fly south to El Calafate, gateway to the glaciers.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 4, title: "Perito Moreno Glacier", description: "Full day at the incredible Perito Moreno glacier.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 5, title: "El Chaltén", description: "Travel to El Chaltén for trekking.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 6, title: "Fitz Roy Trek", description: "Trek to Laguna de los Tres with views of Mt Fitz Roy.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 7, title: "Cross to Chile", description: "Cross the border into Chile and travel to Torres del Paine.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 8, title: "Torres del Paine", description: "Full day exploring Torres del Paine National Park.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Torres del Paine", description: "Trek to the base of the Torres.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 10, title: "Torres del Paine", description: "Visit Grey Glacier and Lago Grey.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 11, title: "Punta Arenas", description: "Travel to Punta Arenas. Visit penguin colony.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 12, title: "Fly to Santiago", description: "Fly to Santiago, Chile's vibrant capital.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 13, title: "Santiago", description: "City tour. Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 14, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "PA-2026-10-10", startDate: "2026-10-10", endDate: "2026-10-23", price: 5065, status: "Available" },
      { id: "PA-2026-11-07", startDate: "2026-11-07", endDate: "2026-11-20", price: 5065, status: "Guaranteed" },
      { id: "PA-2026-12-05", startDate: "2026-12-05", endDate: "2026-12-18", price: 5295, status: "Available" },
      { id: "PA-2027-01-10", startDate: "2027-01-10", endDate: "2027-01-23", price: 5295, status: "Limited" },
      { id: "PA-2027-02-07", startDate: "2027-02-07", endDate: "2027-02-20", price: 5065, status: "Available" },
    ],
    relatedSlugs: ["japan-in-depth", "south-africa-eswatini", "cycle-cuba"],
  },
  "cycle-cuba": {
    slug: "cycle-cuba",
    title: "Cycle Cuba!",
    destination: "Cuba",
    country: "Cuba",
    tripType: "Cycling",
    duration: "15 Days",
    durationDays: 15,
    groupSize: "8-16",
    physicalRating: 3,
    price: 2895,
    imageUrl: "/images/explore/eon-gas.jpg",
    galleryImages: ["/images/explore/eon-gas.jpg"],
    tripCode: "CCC",
    overview:
      "Cycle through the colourful streets and lush countryside of Cuba on this 15-day adventure. Ride past tobacco fields, through colonial towns and along the stunning Vinales valley, experiencing Cuba's unique culture, music and cuisine along the way.",
    highlights: [
      "Cycle through the stunning Vinales valley",
      "Explore Old Havana's colonial architecture",
      "Ride along quiet country roads past tobacco plantations",
      "Visit the revolutionary city of Trinidad",
      "Enjoy live salsa music and Cuban cocktails",
    ],
    included: ["14 nights accommodation", "All breakfasts, 8 lunches, 7 dinners", "Quality hybrid bicycle", "Support vehicle", "Expert cycling guide"],
    notIncluded: ["International flights", "Travel insurance", "Cuban tourist card", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Havana", description: "Arrive in Havana and transfer to your hotel in the old town.", meals: "Dinner", accommodation: "Casa Particular" },
      { day: 2, title: "Havana exploration", description: "Walking tour of Old Havana. Bike fitting in the afternoon.", meals: "Breakfast", accommodation: "Casa Particular" },
      { day: 3, title: "Havana to Las Terrazas", description: "First day cycling. Ride 65km west through the countryside.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 4, title: "Las Terrazas to Vinales", description: "Cycle 55km to the beautiful Vinales valley.", meals: "Breakfast, Lunch", accommodation: "Casa Particular" },
      { day: 5, title: "Vinales Valley", description: "Cycle through the valley visiting tobacco farms and caves.", meals: "Breakfast, Lunch, Dinner", accommodation: "Casa Particular" },
      { day: 6, title: "Vinales to Soroa", description: "Cycle 70km through lush countryside.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 7, title: "Soroa to Bay of Pigs", description: "Long ride 95km south to the Bay of Pigs.", meals: "Breakfast, Lunch, Dinner", accommodation: "Casa Particular" },
      { day: 8, title: "Bay of Pigs", description: "Rest day with snorkelling in cenotes.", meals: "Breakfast", accommodation: "Casa Particular" },
      { day: 9, title: "Bay of Pigs to Trinidad", description: "Cycle 80km along the coast to colonial Trinidad.", meals: "Breakfast, Lunch", accommodation: "Casa Particular" },
      { day: 10, title: "Trinidad", description: "Free day to explore this UNESCO World Heritage town.", meals: "Breakfast, Dinner", accommodation: "Casa Particular" },
      { day: 11, title: "Trinidad to Sancti Spiritus", description: "Cycle 70km inland.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 12, title: "Sancti Spiritus to Santa Clara", description: "Cycle 90km to Santa Clara, city of Che Guevara.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 13, title: "Santa Clara to Varadero", description: "Final cycling day, 80km to the coast.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 14, title: "Varadero beach day", description: "Free day at the beach. Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 15, title: "Departure", description: "Transfer to Havana airport.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "CCC-2026-10-17", startDate: "2026-10-17", endDate: "2026-10-31", price: 2895, status: "Available" },
      { id: "CCC-2026-11-14", startDate: "2026-11-14", endDate: "2026-11-28", price: 2895, status: "Guaranteed" },
      { id: "CCC-2027-01-09", startDate: "2027-01-09", endDate: "2027-01-23", price: 2995, status: "Available" },
      { id: "CCC-2027-02-06", startDate: "2027-02-06", endDate: "2027-02-20", price: 2995, status: "Limited" },
      { id: "CCC-2027-03-06", startDate: "2027-03-06", endDate: "2027-03-20", price: 2895, status: "Available" },
    ],
    relatedSlugs: ["amalfi-coast-walking", "japan-in-depth", "south-africa-eswatini"],
  },
  "greek-island-hopping": {
    slug: "greek-island-hopping",
    title: "Greek Island Hopping",
    destination: "Greece",
    country: "Greece",
    tripType: "Discovery",
    duration: "10 Days",
    durationDays: 10,
    groupSize: "8-16",
    physicalRating: 2,
    price: 1895,
    imageUrl: "/images/explore/eon-solar.jpg",
    galleryImages: ["/images/explore/eon-solar.jpg"],
    tripCode: "GIH",
    overview: "Island hop through the stunning Greek archipelago, from the white-washed villages of the Cyclades to the turquoise waters of the Dodecanese. Discover ancient ruins, taste authentic Greek cuisine and enjoy the warm hospitality of the islands.",
    highlights: ["Explore the iconic blue-domed churches of Santorini", "Swim in crystal-clear waters off Naxos", "Visit the ancient ruins of Delos", "Taste local wines on a vineyard tour", "Wander the narrow lanes of Mykonos"],
    included: ["9 nights accommodation", "All breakfasts, 4 lunches, 5 dinners", "Inter-island ferries", "Expert English-speaking guide", "All entrance fees"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Athens", description: "Arrive in Athens and transfer to hotel. Welcome dinner.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Athens exploration", description: "Visit the Acropolis, Parthenon and explore the Plaka district.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 3, title: "Ferry to Naxos", description: "Ferry to Naxos. Afternoon exploring the old town.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 4, title: "Naxos", description: "Full day exploring beaches and mountain villages.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 5, title: "Naxos to Santorini", description: "Ferry to Santorini. Sunset in Oia.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 6, title: "Santorini", description: "Hike from Fira to Oia. Wine tasting.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 7, title: "Santorini to Paros", description: "Ferry to Paros. Afternoon at leisure.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 8, title: "Paros & Antiparos", description: "Visit Antiparos cave and beaches.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Paros to Athens", description: "Return ferry. Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 10, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "GIH-2026-05-10", startDate: "2026-05-10", endDate: "2026-05-19", price: 1895, status: "Guaranteed" },
      { id: "GIH-2026-06-07", startDate: "2026-06-07", endDate: "2026-06-16", price: 1995, status: "Available" },
      { id: "GIH-2026-09-13", startDate: "2026-09-13", endDate: "2026-09-22", price: 1895, status: "Available" },
      { id: "GIH-2026-10-04", startDate: "2026-10-04", endDate: "2026-10-13", price: 1795, status: "Limited" },
    ],
    relatedSlugs: ["amalfi-coast-walking", "spain-camino-de-santiago", "iceland-ring-road"],
  },
  "spain-camino-de-santiago": {
    slug: "spain-camino-de-santiago",
    title: "Walk the Camino de Santiago",
    destination: "Spain",
    country: "Spain",
    tripType: "Walking",
    duration: "10 Days",
    durationDays: 10,
    groupSize: "8-14",
    physicalRating: 4,
    price: 1695,
    imageUrl: "/images/explore/eon-solar.jpg",
    galleryImages: ["/images/explore/eon-solar.jpg"],
    tripCode: "SCS",
    overview: "Walk the final 115km of the iconic Camino de Santiago pilgrimage route from Sarria to Santiago de Compostela. Follow ancient paths through lush Galician countryside, stay in charming villages and earn your Compostela certificate.",
    highlights: ["Walk the final stages of the Camino de Santiago", "Arrive at Santiago Cathedral", "Stay in traditional Galician guesthouses", "Sample pintxos and Albariño wine", "Cross the ancient bridge at Portomarín"],
    included: ["9 nights accommodation", "All breakfasts, 3 lunches, 5 dinners", "Luggage transfers between hotels", "Expert walking guide", "Compostela certificate"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Santiago", description: "Arrive and transfer to starting point in Sarria.", meals: "Dinner", accommodation: "Guesthouse" },
      { day: 2, title: "Sarria to Portomarín", description: "Walk 22km through oak forests.", meals: "Breakfast, Lunch", accommodation: "Guesthouse" },
      { day: 3, title: "Portomarín to Palas de Rei", description: "Walk 25km past churches and farmland.", meals: "Breakfast, Dinner", accommodation: "Guesthouse" },
      { day: 4, title: "Palas de Rei to Arzúa", description: "Walk 29km through Galician countryside.", meals: "Breakfast, Lunch", accommodation: "Guesthouse" },
      { day: 5, title: "Arzúa to O Pedrouzo", description: "Walk 19km, the penultimate stage.", meals: "Breakfast, Dinner", accommodation: "Guesthouse" },
      { day: 6, title: "O Pedrouzo to Santiago", description: "Final walk 20km to Santiago Cathedral.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 7, title: "Santiago de Compostela", description: "Free day to explore the city.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 8, title: "Finisterre excursion", description: "Optional trip to Cape Finisterre, the End of the Earth.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Santiago", description: "Farewell dinner and celebration.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 10, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "SCS-2026-04-19", startDate: "2026-04-19", endDate: "2026-04-28", price: 1695, status: "Guaranteed" },
      { id: "SCS-2026-05-10", startDate: "2026-05-10", endDate: "2026-05-19", price: 1695, status: "Available" },
      { id: "SCS-2026-06-14", startDate: "2026-06-14", endDate: "2026-06-23", price: 1795, status: "Available" },
      { id: "SCS-2026-09-06", startDate: "2026-09-06", endDate: "2026-09-15", price: 1695, status: "Limited" },
    ],
    relatedSlugs: ["amalfi-coast-walking", "greek-island-hopping", "portugal-highlights"],
  },
  "iceland-ring-road": {
    slug: "iceland-ring-road",
    title: "Iceland's Ring Road",
    destination: "Iceland",
    country: "Iceland",
    tripType: "Discovery",
    duration: "10 Days",
    durationDays: 10,
    groupSize: "6-14",
    physicalRating: 2,
    price: 3495,
    imageUrl: "/images/explore/eon-emobility.jpg",
    galleryImages: ["/images/explore/eon-emobility.jpg"],
    tripCode: "IRR",
    overview: "Circumnavigate Iceland on Route 1, witnessing some of the most dramatic landscapes on Earth. From thundering waterfalls and black sand beaches to erupting geysers and glacier lagoons, this is nature at its most raw.",
    highlights: ["Drive Iceland's famous Ring Road", "Walk behind Seljalandsfoss waterfall", "Visit Jökulsárlón glacier lagoon", "Relax in natural hot springs", "Spot puffins and whales"],
    included: ["9 nights accommodation", "All breakfasts, 4 lunches, 6 dinners", "Expert guide/driver", "All transport", "Hot spring entrance"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Reykjavik", description: "Arrive and settle into Reykjavik.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Golden Circle", description: "Visit Thingvellir, Geysir and Gullfoss.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 3, title: "South Coast", description: "Seljalandsfoss, Skógafoss and Reynisfjara black sand beach.", meals: "Breakfast, Lunch, Dinner", accommodation: "Guesthouse" },
      { day: 4, title: "Vatnajökull", description: "Glacier walk and Jökulsárlón glacier lagoon.", meals: "Breakfast, Dinner", accommodation: "Guesthouse" },
      { day: 5, title: "East Fjords", description: "Drive through the stunning East Fjords.", meals: "Breakfast, Lunch", accommodation: "Guesthouse" },
      { day: 6, title: "Mývatn", description: "Explore Lake Mývatn volcanic landscapes.", meals: "Breakfast, Dinner", accommodation: "Guesthouse" },
      { day: 7, title: "Húsavík & Dettifoss", description: "Whale watching and Europe's most powerful waterfall.", meals: "Breakfast, Lunch, Dinner", accommodation: "Guesthouse" },
      { day: 8, title: "Akureyri", description: "Explore Iceland's northern capital.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Snæfellsnes Peninsula", description: "Visit the iconic Kirkjufell mountain.", meals: "Breakfast, Dinner", accommodation: "Guesthouse" },
      { day: 10, title: "Departure", description: "Return to Reykjavik. Trip ends.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "IRR-2026-06-07", startDate: "2026-06-07", endDate: "2026-06-16", price: 3495, status: "Available" },
      { id: "IRR-2026-06-28", startDate: "2026-06-28", endDate: "2026-07-07", price: 3695, status: "Guaranteed" },
      { id: "IRR-2026-07-19", startDate: "2026-07-19", endDate: "2026-07-28", price: 3695, status: "Limited" },
      { id: "IRR-2026-08-09", startDate: "2026-08-09", endDate: "2026-08-18", price: 3495, status: "Available" },
    ],
    relatedSlugs: ["greek-island-hopping", "adventures-in-patagonia", "amalfi-coast-walking"],
  },
  "portugal-highlights": {
    slug: "portugal-highlights",
    title: "Portugal Highlights",
    destination: "Portugal",
    country: "Portugal",
    tripType: "Discovery",
    duration: "9 Days",
    durationDays: 9,
    groupSize: "8-16",
    physicalRating: 2,
    price: 1595,
    imageUrl: "/images/explore/eon-solar.jpg",
    galleryImages: ["/images/explore/eon-solar.jpg"],
    tripCode: "PH",
    overview: "Discover the best of Portugal from Lisbon's vibrant neighbourhoods to Porto's port wine cellars. Visit fairytale palaces in Sintra, surf towns on the Algarve coast, and the medieval university city of Coimbra.",
    highlights: ["Explore Lisbon's historic Alfama district", "Visit the fairytale Pena Palace in Sintra", "Tour Porto's famous port wine cellars", "Cruise the Douro Valley", "Walk the Algarve's golden cliffs"],
    included: ["8 nights accommodation", "All breakfasts, 3 lunches, 4 dinners", "Expert local guide", "Internal transport", "All entrance fees"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Lisbon", description: "Arrive and explore the Alfama district.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Lisbon", description: "Visit Belém Tower, Jerónimos Monastery.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 3, title: "Sintra", description: "Day trip to Sintra's palaces and gardens.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 4, title: "Alentejo", description: "Travel through the Alentejo region.", meals: "Breakfast, Lunch, Dinner", accommodation: "Guesthouse" },
      { day: 5, title: "Algarve Coast", description: "Explore dramatic coastal cliffs and beaches.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 6, title: "Coimbra", description: "Visit the historic university city.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 7, title: "Douro Valley", description: "Cruise the Douro and visit vineyards.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 8, title: "Porto", description: "Explore Porto and taste port wine.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "PH-2026-04-11", startDate: "2026-04-11", endDate: "2026-04-19", price: 1595, status: "Guaranteed" },
      { id: "PH-2026-05-09", startDate: "2026-05-09", endDate: "2026-05-17", price: 1595, status: "Available" },
      { id: "PH-2026-06-06", startDate: "2026-06-06", endDate: "2026-06-14", price: 1695, status: "Available" },
      { id: "PH-2026-09-12", startDate: "2026-09-12", endDate: "2026-09-20", price: 1595, status: "Limited" },
      { id: "PH-2026-10-10", startDate: "2026-10-10", endDate: "2026-10-18", price: 1495, status: "Available" },
    ],
    relatedSlugs: ["spain-camino-de-santiago", "amalfi-coast-walking", "greek-island-hopping"],
  },
  "croatia-sailing": {
    slug: "croatia-sailing",
    title: "Cruise the Croatian Coast",
    destination: "Croatia",
    country: "Croatia",
    tripType: "Boat",
    duration: "8 Days",
    durationDays: 8,
    groupSize: "12-20",
    physicalRating: 1,
    price: 1795,
    imageUrl: "/images/explore/eon-solar.jpg",
    galleryImages: ["/images/explore/eon-solar.jpg"],
    tripCode: "CRC",
    overview: "Sail the stunning Dalmatian coast aboard a traditional gulet. Visit the medieval walled city of Dubrovnik, swim in secluded coves, explore the islands of Hvar and Korčula, and watch the sun set over the Adriatic.",
    highlights: ["Explore Dubrovnik's old town walls", "Swim in hidden coves along the coast", "Visit the lavender island of Hvar", "Taste local Croatian wines", "Sail on a traditional wooden gulet"],
    included: ["7 nights on gulet", "All breakfasts, 5 lunches, 4 dinners", "Captain and crew", "Harbour fees", "Kayaking equipment"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Dubrovnik", description: "Board your gulet in Dubrovnik.", meals: "Dinner", accommodation: "Gulet" },
      { day: 2, title: "Dubrovnik old town", description: "Explore the UNESCO old town.", meals: "Breakfast, Lunch", accommodation: "Gulet" },
      { day: 3, title: "Mljet", description: "Visit Mljet National Park lakes.", meals: "Breakfast, Lunch, Dinner", accommodation: "Gulet" },
      { day: 4, title: "Korčula", description: "Explore Marco Polo's birthplace.", meals: "Breakfast, Lunch", accommodation: "Gulet" },
      { day: 5, title: "Hvar", description: "Visit the lavender island.", meals: "Breakfast, Dinner", accommodation: "Gulet" },
      { day: 6, title: "Vis", description: "Swim in the Blue Cave.", meals: "Breakfast, Lunch, Dinner", accommodation: "Gulet" },
      { day: 7, title: "Brač to Split", description: "Visit Zlatni Rat beach, arrive in Split.", meals: "Breakfast, Lunch, Dinner", accommodation: "Gulet" },
      { day: 8, title: "Departure", description: "Disembark in Split.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "CRC-2026-05-23", startDate: "2026-05-23", endDate: "2026-05-30", price: 1795, status: "Available" },
      { id: "CRC-2026-06-13", startDate: "2026-06-13", endDate: "2026-06-20", price: 1995, status: "Guaranteed" },
      { id: "CRC-2026-07-11", startDate: "2026-07-11", endDate: "2026-07-18", price: 2195, status: "Limited" },
      { id: "CRC-2026-09-05", startDate: "2026-09-05", endDate: "2026-09-12", price: 1895, status: "Available" },
    ],
    relatedSlugs: ["greek-island-hopping", "amalfi-coast-walking", "portugal-highlights"],
  },
  "cycle-tuscany": {
    slug: "cycle-tuscany",
    title: "Cycle Tuscany",
    destination: "Italy",
    country: "Italy",
    tripType: "Cycling",
    duration: "8 Days",
    durationDays: 8,
    groupSize: "8-14",
    physicalRating: 3,
    price: 1695,
    imageUrl: "/images/explore/eon-solar.jpg",
    galleryImages: ["/images/explore/eon-solar.jpg"],
    tripCode: "CTI",
    overview: "Cycle through the rolling hills of Tuscany, past vineyards, olive groves and medieval hill towns. Stay in charming agriturismo properties, taste Chianti wines at source and discover the Renaissance treasures of Florence and Siena.",
    highlights: ["Cycle through the Chianti wine region", "Visit the medieval towers of San Gimignano", "Explore Florence's Renaissance art", "Wine tasting at a Tuscan vineyard", "Stay in traditional agriturismo properties"],
    included: ["7 nights accommodation", "All breakfasts, 3 lunches, 5 dinners", "Quality hybrid bicycle", "Support vehicle", "Expert cycling guide"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Florence", description: "Arrive and bike fitting.", meals: "Dinner", accommodation: "Agriturismo" },
      { day: 2, title: "Florence to Chianti", description: "Cycle 50km into the Chianti hills.", meals: "Breakfast, Lunch, Dinner", accommodation: "Agriturismo" },
      { day: 3, title: "Chianti vineyards", description: "Cycle 40km through vineyards.", meals: "Breakfast, Lunch", accommodation: "Agriturismo" },
      { day: 4, title: "Siena", description: "Cycle to Siena, explore the Piazza del Campo.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 5, title: "San Gimignano", description: "Cycle 45km to the medieval towers.", meals: "Breakfast, Lunch, Dinner", accommodation: "Agriturismo" },
      { day: 6, title: "Val d'Orcia", description: "Cycle through UNESCO landscape.", meals: "Breakfast, Dinner", accommodation: "Agriturismo" },
      { day: 7, title: "Montepulciano", description: "Wine tasting. Return ride.", meals: "Breakfast, Lunch, Dinner", accommodation: "Agriturismo" },
      { day: 8, title: "Departure", description: "Transfer to Florence.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "CTI-2026-04-18", startDate: "2026-04-18", endDate: "2026-04-25", price: 1695, status: "Guaranteed" },
      { id: "CTI-2026-05-16", startDate: "2026-05-16", endDate: "2026-05-23", price: 1695, status: "Available" },
      { id: "CTI-2026-09-12", startDate: "2026-09-12", endDate: "2026-09-19", price: 1695, status: "Available" },
      { id: "CTI-2026-10-03", startDate: "2026-10-03", endDate: "2026-10-10", price: 1595, status: "Limited" },
    ],
    relatedSlugs: ["amalfi-coast-walking", "cycle-cuba", "spain-camino-de-santiago"],
  },
  "turkey-discovery": {
    slug: "turkey-discovery",
    title: "Turkey Discovery",
    destination: "Turkey",
    country: "Turkey",
    tripType: "Discovery",
    duration: "12 Days",
    durationDays: 12,
    groupSize: "8-16",
    physicalRating: 2,
    price: 1895,
    imageUrl: "/images/explore/eon-strom.jpg",
    galleryImages: ["/images/explore/eon-strom.jpg"],
    tripCode: "TD",
    overview: "Explore the crossroads of East and West on this 12-day tour of Turkey. From the mosques of Istanbul to the fairy chimneys of Cappadocia, the ancient ruins of Ephesus and the turquoise coast, this trip covers all the highlights.",
    highlights: ["Explore Istanbul's Blue Mosque and Grand Bazaar", "Hot air balloon over Cappadocia", "Visit the ancient city of Ephesus", "Swim in Pamukkale's thermal pools", "Cruise the turquoise Aegean coast"],
    included: ["11 nights accommodation", "All breakfasts, 5 lunches, 6 dinners", "Expert local guide", "All transport", "All entrance fees"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips", "Hot air balloon (optional)"],
    itinerary: [
      { day: 1, title: "Arrive Istanbul", description: "Arrive and transfer to hotel.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Istanbul", description: "Visit Blue Mosque, Hagia Sophia, Grand Bazaar.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 3, title: "Istanbul to Ankara", description: "Travel to the capital.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 4, title: "Ankara to Cappadocia", description: "Drive to the fairy chimneys.", meals: "Breakfast, Dinner", accommodation: "Cave Hotel" },
      { day: 5, title: "Cappadocia", description: "Explore underground cities and valleys.", meals: "Breakfast, Lunch, Dinner", accommodation: "Cave Hotel" },
      { day: 6, title: "Cappadocia", description: "Optional hot air balloon ride.", meals: "Breakfast", accommodation: "Cave Hotel" },
      { day: 7, title: "Konya", description: "Visit the Mevlana Museum.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 8, title: "Pamukkale", description: "Visit the white thermal terraces.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Ephesus", description: "Explore the ancient Roman city.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 10, title: "Aegean Coast", description: "Cruise along the turquoise coast.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 11, title: "Istanbul return", description: "Fly back to Istanbul. Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 12, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "TD-2026-04-05", startDate: "2026-04-05", endDate: "2026-04-16", price: 1895, status: "Guaranteed" },
      { id: "TD-2026-05-03", startDate: "2026-05-03", endDate: "2026-05-14", price: 1895, status: "Available" },
      { id: "TD-2026-06-07", startDate: "2026-06-07", endDate: "2026-06-18", price: 1995, status: "Available" },
      { id: "TD-2026-09-06", startDate: "2026-09-06", endDate: "2026-09-17", price: 1895, status: "Limited" },
      { id: "TD-2026-10-04", startDate: "2026-10-04", endDate: "2026-10-15", price: 1795, status: "Available" },
    ],
    relatedSlugs: ["greek-island-hopping", "japan-in-depth", "morocco-discovery"],
  },
  "morocco-discovery": {
    slug: "morocco-discovery",
    title: "Discover Morocco",
    destination: "Morocco",
    country: "Morocco",
    tripType: "Discovery",
    duration: "10 Days",
    durationDays: 10,
    groupSize: "8-16",
    physicalRating: 2,
    price: 1295,
    imageUrl: "/images/explore/eon-waermepumpe.jpg",
    galleryImages: ["/images/explore/eon-waermepumpe.jpg"],
    tripCode: "MD",
    overview: "Journey through Morocco from the bustling medinas of Marrakech and Fez to the vast Sahara Desert. Camp under the stars, ride camels across golden dunes, explore the Atlas Mountains and immerse yourself in vibrant Moroccan culture.",
    highlights: ["Camp overnight in the Sahara Desert", "Camel trek across Erg Chebbi dunes", "Explore the ancient medina of Fez", "Visit the blue city of Chefchaouen", "Cross the High Atlas Mountains"],
    included: ["9 nights accommodation", "All breakfasts, 4 lunches, 5 dinners", "Expert local guide", "All transport", "Camel trek"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Marrakech", description: "Arrive and explore the Djemaa el-Fna.", meals: "Dinner", accommodation: "Riad" },
      { day: 2, title: "Marrakech", description: "Guided tour of the medina and souks.", meals: "Breakfast", accommodation: "Riad" },
      { day: 3, title: "Atlas Mountains", description: "Drive over the Tizi n'Tichka pass.", meals: "Breakfast, Lunch, Dinner", accommodation: "Kasbah" },
      { day: 4, title: "Todra Gorge", description: "Explore the dramatic gorge.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 5, title: "Sahara Desert", description: "Camel trek into the Erg Chebbi dunes.", meals: "Breakfast, Dinner", accommodation: "Desert Camp" },
      { day: 6, title: "Desert to Fez", description: "Long drive through the Middle Atlas.", meals: "Breakfast, Lunch, Dinner", accommodation: "Riad" },
      { day: 7, title: "Fez", description: "Full day in the ancient medina.", meals: "Breakfast", accommodation: "Riad" },
      { day: 8, title: "Chefchaouen", description: "Visit the blue city.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Return to Marrakech", description: "Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Riad" },
      { day: 10, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "MD-2026-03-14", startDate: "2026-03-14", endDate: "2026-03-23", price: 1295, status: "Guaranteed" },
      { id: "MD-2026-04-11", startDate: "2026-04-11", endDate: "2026-04-20", price: 1295, status: "Available" },
      { id: "MD-2026-10-03", startDate: "2026-10-03", endDate: "2026-10-12", price: 1295, status: "Available" },
      { id: "MD-2026-11-07", startDate: "2026-11-07", endDate: "2026-11-16", price: 1195, status: "Available" },
    ],
    relatedSlugs: ["turkey-discovery", "jordan-petra", "south-africa-eswatini"],
  },
  "jordan-petra": {
    slug: "jordan-petra",
    title: "Jordan - Petra & Wadi Rum",
    destination: "Jordan",
    country: "Jordan",
    tripType: "Discovery",
    duration: "8 Days",
    durationDays: 8,
    groupSize: "8-16",
    physicalRating: 2,
    price: 1595,
    imageUrl: "/images/explore/eon-waermepumpe.jpg",
    galleryImages: ["/images/explore/eon-waermepumpe.jpg"],
    tripCode: "JP",
    overview: "Discover the ancient wonders of Jordan, from the rose-red city of Petra to the dramatic desert landscapes of Wadi Rum. Float in the Dead Sea, explore Roman ruins at Jerash and camp under the stars with Bedouin guides.",
    highlights: ["Explore the rose-red city of Petra", "Camp in Wadi Rum desert", "Float in the Dead Sea", "Visit Roman ruins at Jerash", "Jeep safari through Wadi Rum"],
    included: ["7 nights accommodation", "All breakfasts, 3 lunches, 5 dinners", "Expert local guide", "All transport", "Petra entrance"],
    notIncluded: ["International flights", "Travel insurance", "Jordan visa", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Amman", description: "Arrive and transfer to hotel.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Jerash & Ajloun", description: "Visit Roman ruins and crusader castle.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 3, title: "Dead Sea", description: "Float in the lowest point on Earth.", meals: "Breakfast, Dinner", accommodation: "Resort" },
      { day: 4, title: "Madaba to Petra", description: "Visit mosaics and drive King's Highway.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 5, title: "Petra", description: "Full day exploring the ancient city.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 6, title: "Petra to Wadi Rum", description: "Travel to Wadi Rum for jeep safari.", meals: "Breakfast, Lunch, Dinner", accommodation: "Desert Camp" },
      { day: 7, title: "Wadi Rum to Amman", description: "Return drive. Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 8, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "JP-2026-03-21", startDate: "2026-03-21", endDate: "2026-03-28", price: 1595, status: "Guaranteed" },
      { id: "JP-2026-04-18", startDate: "2026-04-18", endDate: "2026-04-25", price: 1595, status: "Available" },
      { id: "JP-2026-10-03", startDate: "2026-10-03", endDate: "2026-10-10", price: 1595, status: "Available" },
      { id: "JP-2026-11-07", startDate: "2026-11-07", endDate: "2026-11-14", price: 1495, status: "Available" },
    ],
    relatedSlugs: ["turkey-discovery", "morocco-discovery", "japan-in-depth"],
  },
  "vietnam-highlights": {
    slug: "vietnam-highlights",
    title: "Vietnam Highlights",
    destination: "Vietnam",
    country: "Vietnam",
    tripType: "Discovery",
    duration: "14 Days",
    durationDays: 14,
    groupSize: "8-16",
    physicalRating: 2,
    price: 2195,
    imageUrl: "/images/explore/eon-strom.jpg",
    galleryImages: ["/images/explore/eon-strom.jpg"],
    tripCode: "VH",
    overview: "Travel the length of Vietnam from Hanoi's Old Quarter to the bustling streets of Ho Chi Minh City. Cruise Ha Long Bay, cycle through Hoi An's lantern-lit streets, explore the imperial citadel of Hue and taste incredible Vietnamese cuisine.",
    highlights: ["Cruise overnight on Ha Long Bay", "Cycle through Hoi An's old town", "Visit the Cu Chi Tunnels", "Explore Hue's Imperial Citadel", "Sample street food in Hanoi"],
    included: ["13 nights accommodation", "All breakfasts, 5 lunches, 4 dinners", "Expert local guide", "Internal flights", "Ha Long Bay cruise"],
    notIncluded: ["International flights", "Travel insurance", "Vietnam visa", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Hanoi", description: "Arrive in Hanoi's Old Quarter.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Hanoi", description: "Walking tour. Water puppet show.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 3, title: "Ha Long Bay", description: "Board junk boat for overnight cruise.", meals: "Breakfast, Lunch, Dinner", accommodation: "Junk Boat" },
      { day: 4, title: "Ha Long Bay to Hanoi", description: "Morning tai chi. Return cruise.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 5, title: "Fly to Hue", description: "Explore the Imperial Citadel.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 6, title: "Hue", description: "Visit royal tombs and Thien Mu Pagoda.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 7, title: "Hue to Hoi An", description: "Drive over the Hai Van Pass.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 8, title: "Hoi An", description: "Cycling tour and cooking class.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Hoi An free day", description: "Beach time or tailor shopping.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 10, title: "Fly to Ho Chi Minh City", description: "Explore Saigon.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 11, title: "Cu Chi Tunnels", description: "Visit the famous tunnel network.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 12, title: "Mekong Delta", description: "Day trip by boat.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 13, title: "Saigon", description: "Free day. Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 14, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "VH-2026-03-07", startDate: "2026-03-07", endDate: "2026-03-20", price: 2195, status: "Guaranteed" },
      { id: "VH-2026-04-04", startDate: "2026-04-04", endDate: "2026-04-17", price: 2195, status: "Available" },
      { id: "VH-2026-10-03", startDate: "2026-10-03", endDate: "2026-10-16", price: 2195, status: "Available" },
      { id: "VH-2026-11-07", startDate: "2026-11-07", endDate: "2026-11-20", price: 2095, status: "Available" },
    ],
    relatedSlugs: ["japan-in-depth", "india-rajasthan", "sri-lanka-explorer"],
  },
  "india-rajasthan": {
    slug: "india-rajasthan",
    title: "Rajasthan - Land of the Maharajas",
    destination: "India",
    country: "India",
    tripType: "Discovery",
    duration: "14 Days",
    durationDays: 14,
    groupSize: "8-16",
    physicalRating: 2,
    price: 1695,
    imageUrl: "/images/explore/eon-strom.jpg",
    galleryImages: ["/images/explore/eon-strom.jpg"],
    tripCode: "IR",
    overview: "Journey through the vibrant colours and rich heritage of Rajasthan. Visit the pink city of Jaipur, the blue city of Jodhpur, the golden city of Jaisalmer and the romantic lake city of Udaipur. Experience camel safaris, palace stays and the Taj Mahal.",
    highlights: ["Visit the Taj Mahal at sunrise", "Explore the Amber Fort in Jaipur", "Camel safari in the Thar Desert", "Stay in heritage havelis", "Experience a traditional Rajasthani feast"],
    included: ["13 nights accommodation", "All breakfasts, 5 lunches, 6 dinners", "Expert local guide", "All transport", "All entrance fees"],
    notIncluded: ["International flights", "Travel insurance", "India visa", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Delhi", description: "Arrive in Delhi.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Delhi", description: "Old and New Delhi tour.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 3, title: "Agra", description: "Travel to Agra, visit Taj Mahal.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 4, title: "Agra to Jaipur", description: "Visit Fatehpur Sikri en route.", meals: "Breakfast, Dinner", accommodation: "Haveli" },
      { day: 5, title: "Jaipur", description: "Amber Fort, City Palace.", meals: "Breakfast, Lunch, Dinner", accommodation: "Haveli" },
      { day: 6, title: "Jaipur to Pushkar", description: "Sacred lake and Brahma temple.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 7, title: "Pushkar to Jodhpur", description: "Mehrangarh Fort.", meals: "Breakfast, Lunch, Dinner", accommodation: "Haveli" },
      { day: 8, title: "Jodhpur", description: "Explore the Blue City.", meals: "Breakfast, Dinner", accommodation: "Haveli" },
      { day: 9, title: "Jaisalmer", description: "Golden Fort and havelis.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 10, title: "Thar Desert", description: "Camel safari and desert camp.", meals: "Breakfast, Lunch, Dinner", accommodation: "Desert Camp" },
      { day: 11, title: "Jaisalmer to Udaipur", description: "Long drive through Rajasthan.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 12, title: "Udaipur", description: "City Palace and Lake Pichola.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 13, title: "Udaipur", description: "Free day. Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 14, title: "Departure", description: "Fly to Delhi. Trip ends.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "IR-2026-10-10", startDate: "2026-10-10", endDate: "2026-10-23", price: 1695, status: "Guaranteed" },
      { id: "IR-2026-11-07", startDate: "2026-11-07", endDate: "2026-11-20", price: 1695, status: "Available" },
      { id: "IR-2027-01-10", startDate: "2027-01-10", endDate: "2027-01-23", price: 1695, status: "Available" },
      { id: "IR-2027-02-07", startDate: "2027-02-07", endDate: "2027-02-20", price: 1595, status: "Available" },
    ],
    relatedSlugs: ["vietnam-highlights", "japan-in-depth", "sri-lanka-explorer"],
  },
  "sri-lanka-explorer": {
    slug: "sri-lanka-explorer",
    title: "Sri Lanka Explorer",
    destination: "Sri Lanka",
    country: "Sri Lanka",
    tripType: "Discovery",
    duration: "12 Days",
    durationDays: 12,
    groupSize: "8-16",
    physicalRating: 2,
    price: 1895,
    imageUrl: "/images/explore/eon-strom.jpg",
    galleryImages: ["/images/explore/eon-strom.jpg"],
    tripCode: "SLE",
    overview: "Explore the teardrop island of Sri Lanka from ancient temples and lush tea plantations to pristine beaches and wildlife-rich national parks. Climb Sigiriya Rock, ride the iconic hill-country train and spot elephants and leopards.",
    highlights: ["Climb the ancient fortress of Sigiriya", "Ride the iconic train through tea country", "Safari in Yala National Park", "Visit the Temple of the Tooth in Kandy", "Relax on palm-fringed beaches"],
    included: ["11 nights accommodation", "All breakfasts, 4 lunches, 5 dinners", "Expert local guide", "All transport", "Safari jeep"],
    notIncluded: ["International flights", "Travel insurance", "Sri Lanka ETA visa", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Colombo", description: "Arrive and transfer to Negombo.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Sigiriya", description: "Climb the ancient rock fortress.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 3, title: "Polonnaruwa", description: "Ancient ruins tour.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 4, title: "Dambulla", description: "Cave temples and village walk.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 5, title: "Kandy", description: "Temple of the Tooth. Cultural show.", meals: "Breakfast", accommodation: "Hotel" },
      { day: 6, title: "Kandy to Nuwara Eliya", description: "Train through tea country.", meals: "Breakfast, Lunch, Dinner", accommodation: "Guesthouse" },
      { day: 7, title: "Nuwara Eliya", description: "Tea plantation visit.", meals: "Breakfast", accommodation: "Guesthouse" },
      { day: 8, title: "Ella", description: "Nine Arches Bridge and Little Adam's Peak.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Yala", description: "Safari in Yala National Park.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 10, title: "South Coast", description: "Whale watching. Beach time.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 11, title: "Galle", description: "Explore the colonial fort city.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 12, title: "Departure", description: "Transfer to Colombo airport.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "SLE-2026-10-17", startDate: "2026-10-17", endDate: "2026-10-28", price: 1895, status: "Guaranteed" },
      { id: "SLE-2026-11-14", startDate: "2026-11-14", endDate: "2026-11-25", price: 1895, status: "Available" },
      { id: "SLE-2027-01-10", startDate: "2027-01-10", endDate: "2027-01-21", price: 1895, status: "Available" },
      { id: "SLE-2027-02-14", startDate: "2027-02-14", endDate: "2027-02-25", price: 1795, status: "Available" },
    ],
    relatedSlugs: ["india-rajasthan", "vietnam-highlights", "japan-in-depth"],
  },
  "costa-rica-wildlife": {
    slug: "costa-rica-wildlife",
    title: "Costa Rica Wildlife & Volcanoes",
    destination: "Costa Rica",
    country: "Costa Rica",
    tripType: "Wildlife",
    duration: "12 Days",
    durationDays: 12,
    groupSize: "8-16",
    physicalRating: 2,
    price: 2495,
    imageUrl: "/images/explore/eon-emobility.jpg",
    galleryImages: ["/images/explore/eon-emobility.jpg"],
    tripCode: "CRW",
    overview: "Discover Costa Rica's incredible biodiversity on this wildlife-focused adventure. From cloud forests teeming with resplendent quetzals to volcanic hot springs and mangrove-lined coasts, this is nature at its most spectacular.",
    highlights: ["Spot sloths, toucans and monkeys in Monteverde", "Hike Arenal Volcano trails", "Visit Tortuguero sea turtle sanctuary", "Zip-line through the cloud forest canopy", "Relax in volcanic hot springs"],
    included: ["11 nights accommodation", "All breakfasts, 5 lunches, 5 dinners", "Expert naturalist guide", "All transport", "National park fees"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive San José", description: "Arrive and transfer to hotel.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Tortuguero", description: "Boat ride through canals.", meals: "Breakfast, Lunch, Dinner", accommodation: "Eco Lodge" },
      { day: 3, title: "Tortuguero", description: "Canal boat safari.", meals: "Breakfast, Lunch, Dinner", accommodation: "Eco Lodge" },
      { day: 4, title: "Arenal Volcano", description: "Hot springs and hanging bridges.", meals: "Breakfast, Lunch", accommodation: "Lodge" },
      { day: 5, title: "Arenal", description: "Volcano hike and waterfall.", meals: "Breakfast, Dinner", accommodation: "Lodge" },
      { day: 6, title: "Monteverde", description: "Cloud forest reserve walk.", meals: "Breakfast", accommodation: "Lodge" },
      { day: 7, title: "Monteverde", description: "Zip-line and night walk.", meals: "Breakfast, Lunch, Dinner", accommodation: "Lodge" },
      { day: 8, title: "Manuel Antonio", description: "Travel to the Pacific coast.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 9, title: "Manuel Antonio", description: "National park wildlife walk.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 10, title: "Osa Peninsula", description: "Corcovado National Park.", meals: "Breakfast, Lunch, Dinner", accommodation: "Eco Lodge" },
      { day: 11, title: "San José", description: "Return. Farewell dinner.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 12, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "CRW-2026-11-07", startDate: "2026-11-07", endDate: "2026-11-18", price: 2495, status: "Guaranteed" },
      { id: "CRW-2026-12-05", startDate: "2026-12-05", endDate: "2026-12-16", price: 2695, status: "Available" },
      { id: "CRW-2027-01-10", startDate: "2027-01-10", endDate: "2027-01-21", price: 2495, status: "Available" },
      { id: "CRW-2027-02-07", startDate: "2027-02-07", endDate: "2027-02-18", price: 2495, status: "Limited" },
    ],
    relatedSlugs: ["cycle-cuba", "adventures-in-patagonia", "south-africa-eswatini"],
  },
  "norway-fjords": {
    slug: "norway-fjords",
    title: "Norway's Fjords & Northern Lights",
    destination: "Norway",
    country: "Norway",
    tripType: "Discovery",
    duration: "8 Days",
    durationDays: 8,
    groupSize: "6-14",
    physicalRating: 2,
    price: 2895,
    imageUrl: "/images/explore/eon-emobility.jpg",
    galleryImages: ["/images/explore/eon-emobility.jpg"],
    tripCode: "NF",
    overview: "Discover Norway's dramatic fjord landscapes on this winter adventure. Chase the Northern Lights, cruise Geirangerfjord, ride the iconic Flåm Railway and experience the magic of Arctic Norway.",
    highlights: ["Chase the Northern Lights", "Cruise Geirangerfjord", "Ride the Flåm Railway", "Visit the Arctic city of Tromsø", "Dog sledding excursion"],
    included: ["7 nights accommodation", "All breakfasts, 3 lunches, 5 dinners", "Expert guide", "All transport", "Northern Lights excursion"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips"],
    itinerary: [
      { day: 1, title: "Arrive Oslo", description: "Arrive in Oslo.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Oslo to Bergen", description: "Scenic train journey.", meals: "Breakfast, Lunch", accommodation: "Hotel" },
      { day: 3, title: "Bergen", description: "Bryggen wharf and Fløibanen funicular.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 4, title: "Geirangerfjord", description: "Cruise the UNESCO fjord.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 5, title: "Flåm Railway", description: "One of the world's great rail journeys.", meals: "Breakfast, Lunch, Dinner", accommodation: "Hotel" },
      { day: 6, title: "Fly to Tromsø", description: "Arctic capital. Dog sledding.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 7, title: "Northern Lights", description: "Evening Northern Lights chase.", meals: "Breakfast, Dinner", accommodation: "Hotel" },
      { day: 8, title: "Departure", description: "Trip ends after breakfast.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "NF-2026-10-17", startDate: "2026-10-17", endDate: "2026-10-24", price: 2895, status: "Available" },
      { id: "NF-2026-11-14", startDate: "2026-11-14", endDate: "2026-11-21", price: 2895, status: "Guaranteed" },
      { id: "NF-2027-01-17", startDate: "2027-01-17", endDate: "2027-01-24", price: 2995, status: "Available" },
      { id: "NF-2027-02-14", startDate: "2027-02-14", endDate: "2027-02-21", price: 2995, status: "Limited" },
    ],
    relatedSlugs: ["iceland-ring-road", "greek-island-hopping", "portugal-highlights"],
  },
  "south-africa-eswatini": {
    slug: "south-africa-eswatini",
    title: "South Africa & Eswatini",
    destination: "South Africa",
    country: "South Africa",
    tripType: "Wildlife",
    duration: "10 Days",
    durationDays: 10,
    groupSize: "6-16",
    physicalRating: 1,
    price: 1395,
    originalPrice: 1695,
    imageUrl: "/images/explore/eon-waermepumpe.jpg",
    galleryImages: ["/images/explore/eon-waermepumpe.jpg"],
    tripCode: "ZK",
    overview:
      "Experience the incredible wildlife, dramatic landscapes and vibrant cultures of South Africa and the Kingdom of Eswatini on this 10-day small group tour. From the Big Five in Kruger National Park to the Panorama Route, this trip is an unforgettable African adventure.",
    highlights: [
      "Game drives in Kruger National Park searching for the Big Five",
      "Drive the spectacular Panorama Route",
      "Visit a traditional Swazi village in Eswatini",
      "Spot hippos and crocodiles on a river cruise",
      "Experience a Zulu cultural village",
    ],
    included: ["9 nights accommodation", "All breakfasts, 4 lunches, 5 dinners", "Expert tour leader", "Game drives in open vehicles", "All park entrance fees"],
    notIncluded: ["International flights", "Travel insurance", "Meals not listed", "Tips", "Visa (if required)"],
    itinerary: [
      { day: 1, title: "Arrive Johannesburg", description: "Arrive and transfer to hotel. Welcome meeting.", meals: "Dinner", accommodation: "Hotel" },
      { day: 2, title: "Panorama Route", description: "Drive the stunning Panorama Route including Blyde River Canyon.", meals: "Breakfast, Lunch", accommodation: "Lodge" },
      { day: 3, title: "Kruger National Park", description: "Full day game drive in Kruger searching for Big Five.", meals: "Breakfast, Lunch, Dinner", accommodation: "Rest Camp" },
      { day: 4, title: "Kruger National Park", description: "Sunrise and sunset game drives with midday rest.", meals: "Breakfast, Lunch, Dinner", accommodation: "Rest Camp" },
      { day: 5, title: "Kruger to Eswatini", description: "Morning game drive then cross into the Kingdom of Eswatini.", meals: "Breakfast", accommodation: "Mountain Lodge" },
      { day: 6, title: "Eswatini", description: "Visit traditional village and craft markets.", meals: "Breakfast, Dinner", accommodation: "Mountain Lodge" },
      { day: 7, title: "Eswatini to Hluhluwe", description: "Travel to Hluhluwe-iMfolozi Park.", meals: "Breakfast", accommodation: "Safari Lodge" },
      { day: 8, title: "Hluhluwe Game Reserve", description: "Game drives in the oldest proclaimed nature reserve in Africa.", meals: "Breakfast, Lunch, Dinner", accommodation: "Safari Lodge" },
      { day: 9, title: "St Lucia", description: "River cruise for hippos and crocodiles. Beach time.", meals: "Breakfast, Dinner", accommodation: "Lodge" },
      { day: 10, title: "Departure", description: "Transfer to Durban airport.", meals: "Breakfast", accommodation: "" },
    ],
    departures: [
      { id: "ZK-2026-05-09", startDate: "2026-05-09", endDate: "2026-05-18", price: 1395, originalPrice: 1695, status: "Guaranteed" },
      { id: "ZK-2026-06-06", startDate: "2026-06-06", endDate: "2026-06-15", price: 1395, originalPrice: 1695, status: "Available" },
      { id: "ZK-2026-07-04", startDate: "2026-07-04", endDate: "2026-07-13", price: 1495, status: "Available" },
      { id: "ZK-2026-08-08", startDate: "2026-08-08", endDate: "2026-08-17", price: 1595, status: "Limited" },
      { id: "ZK-2026-09-05", startDate: "2026-09-05", endDate: "2026-09-14", price: 1495, status: "Available" },
      { id: "ZK-2026-10-03", startDate: "2026-10-03", endDate: "2026-10-12", price: 1395, originalPrice: 1695, status: "Available" },
    ],
    relatedSlugs: ["japan-in-depth", "adventures-in-patagonia", "amalfi-coast-walking"],
  },
}

export function getTour(slug: string): TourDetail | undefined {
  return TOURS[slug]
}

export function getAllTourSlugs(): string[] {
  return Object.keys(TOURS)
}

export function getAllTours(): TourDetail[] {
  return Object.values(TOURS)
}

const REGION_COUNTRY_MAP: Record<string, string[]> = {
  europe: ["Italy", "Greece", "Spain", "Iceland", "Portugal", "Croatia", "Turkey", "Norway", "France", "Germany", "Austria", "Switzerland", "UK", "Ireland", "Sweden", "Denmark", "Finland", "Netherlands", "Belgium", "Czechia", "Poland", "Hungary", "Romania", "Bulgaria", "Albania", "Montenegro", "Bosnia and Herzegovina", "North Macedonia", "Serbia", "Slovenia", "Slovakia", "Estonia", "Latvia", "Lithuania", "Malta", "Cyprus", "Andorra", "Kosovo", "Faroes Islands"],
  asia: ["Japan", "Vietnam", "India", "Sri Lanka", "Thailand", "China", "Nepal", "Myanmar", "Cambodia", "Laos", "Indonesia", "Malaysia", "Mongolia", "Bhutan", "Philippines", "South Korea", "Taiwan", "Uzbekistan", "Kyrgyzstan", "Tajikistan"],
  africa: ["South Africa", "Morocco", "Kenya", "Tanzania", "Uganda", "Rwanda", "Namibia", "Botswana", "Zimbabwe", "Madagascar", "Ethiopia", "Egypt", "Mozambique", "Zambia", "Malawi", "Ghana", "Senegal", "Eswatini"],
  "south-america": ["Argentina", "Chile", "Peru", "Bolivia", "Colombia", "Ecuador", "Brazil", "Uruguay", "Paraguay", "Venezuela", "Guyana", "Suriname"],
  "central-america": ["Costa Rica", "Cuba", "Mexico", "Guatemala", "Belize", "Honduras", "Panama", "Nicaragua", "El Salvador"],
  "middle-east": ["Jordan", "Oman", "Iran", "Israel", "Palestine", "Lebanon"],
  polar: ["Svalbard", "Antarctica", "Greenland", "Arctic"],
  "north-america": ["USA", "Canada", "Alaska"],
  caribbean: ["Jamaica", "Dominican Republic", "Puerto Rico", "Barbados", "Trinidad and Tobago"],
  australasia: ["Australia", "New Zealand", "Papua New Guinea", "Fiji"],
}

export function getToursByRegion(region: string): TourDetail[] {
  const countries = REGION_COUNTRY_MAP[region] || []
  return getAllTours().filter((tour) => {
    const dest = tour.destination.toLowerCase()
    const country = tour.country.toLowerCase()
    return countries.some((c) => c.toLowerCase() === dest || c.toLowerCase() === country)
  })
}

export function getTourCountByRegion(region: string): number {
  return getToursByRegion(region).length
}
